language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.2
    - android-23

  before_install:
    - echo yes | android update sdk --all --filter build-tools-23.0.1 --no-ui --force
    
script:
   - ./gradlew build connectedCheck