language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra

  before_install:
    - echo yes | android update sdk --all --filter build-tools-23.0.1 --no-ui --force
    
script:
   - ./gradlew build connectedCheck